version: '3.8'

services:
  backend:
    image: cmantri2004/taskly-backend
    build: ./backend
    ports:
      - "5555:5555"
    environment:
      - MONGO_URI=mongodb://mongo:27017/taskly
    depends_on:
      - mongo

  frontend:
    image: cmantri2004/taskly-frontend
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend


volumes:
  mongo_data:
